### ISSUE TITLE
Miui13 安卓13出现空指针异常导致闪退

### ISSUE THREAD

**Issue by Otis0227** [577fkj/GenshinProxy#1]
如题

**Comment by 577fkj** [comment]
没机器无法测试

**Comment by Otis0227** [comment]
又试了一下miui13的安卓12版本同样复现该问题

**Comment by 577fkj** [comment]
> 又试了一下miui13的安卓12版本同样复现该问题

我没有安卓机器，目前无法修复。

**Comment by 577fkj** [comment]
能否发一份日志
我尝试修复一下

**Comment by Otis0227** [comment]
java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2017.4.30f1
Device model      : Xiaomi M2011K2C
Device fingerprint: Xiaomi/venus/venus:12/SKQ1.220303.001/22.5.11:user/release-keys

Caused by: java.lang.NullPointerException: url == null
	at com.combosdk.lib.third.okhttp3.Request$Builder.url(Request.java:124)
	at com.miHoYo.support.http.OkhttpHelper.get(OkhttpHelper.java:134)
	at com.miHoYo.support.http.OkhttpHelper.get(OkhttpHelper.java:118)
	at com.miHoYo.support.http.OkhttpHelper.get(OkhttpHelper.java:110)
	at com.combosdk.support.base.BaseInfo.pullClientConfig(BaseInfo.kt:385)
	at com.combosdk.framework.module.info.InfoModuleHandler.invoke(InfoModuleHandler.kt:130)
	at com.combosdk.framework.module.info.InfoModule.invoke(InfoModule.kt:40)
	at com.combosdk.framework.base.FrameworkHandler.invoke(FrameworkHandler.kt:274)
	at com.combosdk.framework.ComboSDK.invoke(ComboSDK.java:52)
	at com.mihoyo.combosdk.ComboForUnity$3.run(ComboForUnity.java:218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1046)

**Comment by 577fkj** [comment]
> 

这是米哈游的问题吧
日志里没有我模块的信息

**Comment by duzhaokun123** [comment]
@Otis0227  会不会是你没填服务器地址

**Comment by duzhaokun123** [comment]
@Otis0227  会不会是你没填服务器地址

**Comment by acgnmoe** [comment]
没加http

**Comment by 577fkj** [comment]
服务器链接未填写完整导致的
